### ISSUE TITLE
Check failures with dplyr 0.7.5 release candidates

### ISSUE THREAD

**Issue by krlmlr** [echasnovski/keyholder#3] opened 2018-04-11 22:25 UTC
https://github.com/tidyverse/dplyr/blob/master/revdep/new-problems.md#keyholder

Could you please take a look and tell me if it's a dplyr problem or something that should be better fixed here? Thanks!

**Comment by krlmlr** [comment] 2018-04-11 22:47
Are the check failures in ruler related? https://github.com/tidyverse/dplyr/blob/master/revdep/new-problems.md#ruler

**Comment by echasnovski** [comment] 2018-04-15 09:18
Thank you for the heads up!

- `keyholder` errors were caused by:
    - Inappropriate test on `group_by_if()`. Fixed in 070c71b3941b0584ccdb08f9c8b1758249a9f369.
    - Not very precise implementation of method for `dplyr`'s `distinct()`. I don't really understand why it stopped working, but in 84e92ad86f29c38ddea15bbc98fa8b0f5b980e7c I made more bulletproof implementation which fixed errors.
- `ruler` errors were caused by deprecation of formula style notation in `funs()`. Fixed in echasnovski/ruler@08b88020741db295cbb1c198c4a742f80f372871 with more concise implementation.

Please, use now GitHub development versions for reverse dependency checks.

Could you tell me when you plan `dplyr` 0.7.5 CRAN release? Will the current GitHub code (master branch) change before release?

**Comment by krlmlr** [comment] 2018-04-15 20:57
Thanks a lot for your feedback!

I don't intend to change anything in the current GitHub version before release, which hopefully happens very soon. In the past, CRAN accepted breaking changes, provided we notified the maintainers of packages now broken.

I do wonder what the original semantics of `funs(~"id")` were. Was this documented behavior? We had problems with `distinct()` and R 3.1 due to https://github.com/r-lib/rlang/issues/486, we're not using `NextMethod()` anymore. Perhaps this also would have solved the problem in *keyholder*, but the patch looks good too.

**Comment by echasnovski** [comment] 2018-04-15 21:13
`funs(~ "id")` was used in `ruler` essentially as renaming function in `select_at()` wrapper to save one step in the pipe. The column `.id` was selected and renamed to `id` in one call. So `funs(~ "id")` was intended to be 'a function that always return "id"'.
Now I don't think it was a very bright idea to use that hack, but it worked.

**Comment by echasnovski** [comment] 2018-05-20 17:38
Fixed in keyholder 0.1.2 and ruler 0.1.3 which are on CRAN now.

**Closed as completed by echasnovski** 2018-05-20 17:38 UTC
